project_id = "jyvojztgptxidemjscgg"

[functions.line-webhook]
verify_jwt = false

[functions.extract-report]
verify_jwt = false

[functions.api-v1-ocr]
verify_jwt = false

[functions.api-v1-extract]
verify_jwt = false

[functions.api-v1-save]
verify_jwt = false

[functions.query-reports]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.check-duplicates]
verify_jwt = false

[functions.search-reports]
verify_jwt = false